### ISSUE TITLE
Short titles / in-page navigation overlap main sidebar menu

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d8#595]
For example:

![short_titles](https://user-images.githubusercontent.com/5913244/64646187-8e9a6c80-d3e4-11e9-8d9a-e16f15ea2704.png)

This appears to be caused by a missing hidden checkbox:
```css
.brg-tr:checked ~ #page, .brg-tr:checked ~ #page .header, .brg-tr:checked ~ #page .topic-nav.sticky {
    left: 300px;
}
```
